export const PROJECTS = [
	{
		id: 0,
		link: 'https://github.com/yashLadha/Bavarder',
		name: 'Bavarder',
		image: 'python',
		content: 'This is a realtime chat server created in Django',
		tags: ['Django', 'Python', 'Socket'],
	},
	{
		id: 9,
		link: 'https://github.com/yashLadha/Parsy',
		name: 'Parsy',
		image: 'flask',
		content: 'Messenger Chat bot for extracting text in image, goto OCR bot',
		tags: ['Flask', 'AWS', 'OCR'],
	},
	{
		id: 1,
		link: 'https://github.com/yashLadha/Incresto',
		name: 'Incresto',
		image: 'angular',
		content: 'This is a sample mini-blog created with Angular 5 and bootstrap.',
		tags: ['Angular', 'JS'],
	},
	{
		id: 8,
		link: 'https://github.com/yashLadha/React-portfolio',
		name: 'React Portfolio',
		image: 'react',
		content: 'This is my portfolio created in React.',
		tags: ['React', 'JS', 'Redux'],
	},
	{
		id: 10,
		link: 'https://github.com/yashLadha/yaas',
		name: 'yaas',
		image: 'nodejs',
		content: 'URL Shortener resembling to my domain',
		tags: ['React', 'Redux', 'ExpressJS', 'Compute Engine'],
	},
	{
		id: 11,
		link: 'https://github.com/yashLadha/cRaxYnM',
		name: 'cRaxYnM',
		image: 'android',
		content: 'Flutter application to generate crazy name generator',
		tags: ['Android', 'Flutter'],
	},
	{
		id: 2,
		link: 'https://github.com/yashLadha/NewPie',
		name: 'Newpie',
		image: 'android',
		content:
			'This is an android app which fetched news from the popular news houses.',
		tags: ['Android', 'Java', 'API'],
	},
	{
		id: 3,
		link: 'https://github.com/yashLadha/10-fast-fingers-hack',
		name: '10-fast-fingers-hack',
		image: 'python',
		content:
			'This is an automation script to achieve `GOOD LEVEL` typing speed on 10-fast fingers.',
		tags: ['Python', 'Automation'],
	},
	{
		id: 4,
		link: 'https://github.com/yashLadha/VIDHI',
		name: 'VIDHI',
		image: 'c',
		content:
			' Mini Compiler created from taking motivation from Kotlin, Scala.',
		tags: ['Compiler', 'YACC+LEX'],
	},
	{
		id: 5,
		link: 'https://github.com/yashLadha/DesignGithub',
		name: 'Design Github',
		image: 'android',
		content:
			'Sample Android application created using Github API and Retrofit library.',
		tags: ['Android', 'Github', 'REST'],
	},
	{
		id: 6,
		link: 'https://github.com/Hatsphere/FHServer',
		name: 'Hatsphere Server',
		image: 'nodejs',
		content:
			'Express based server for the android application, that communicates with the firebase admin sdk.',
		tags: ['ExpressJS', 'Nodejs', 'Firebase'],
	},
	{
		id: 7,
		link: 'https://github.com/Hatsphere/Android-User',
		name: 'Hatsphere user',
		image: 'android',
		content: 'Android application for user HatSphere.',
		tags: ['Android', 'Kotlin', 'Firebase'],
	},
	{
		id: 12,
		link: 'https://github.com/yashLadha/go-moji',
		name: 'go-moji',
		image: 'go',
		content: 'Emojify your git commits',
		tags: ['Golang'],
	},
]
